apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: backend-tests-java-quarkus-jcchbpkv
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tsscui/backend-tests-java-quarkus-jcchbpkv:5147f2ce10b7495c482d69c97852383e8102081c@sha256:6e8aeb6d07ebf875f40d58cf1717da50f5794982c53bc4833d2dbb23288ceef2
          name: container-image
