apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: backend-tests-java-quarkus-jcchbpkv
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tsscui/backend-tests-java-quarkus-jcchbpkv:b5f744afce24b24849a619812bae0b6a22ece4a3@sha256:bf96ae07bfe7c764081bb155be1a46dbad24966ea654aea19454e26169fe56a8
          name: container-image
